### PR TITLE
add french local

### PR DESCRIPTION
**Pull request by yukulele**

### CODE REVIEW

**Comment by Mottie** [comment]
Merci beaucoup! :grin:

**Comment by Mottie** [comment]
Hi @yukulele!

Would you please check my translation of the one additional message I just added.. see https://github.com/CSS-Tricks/The-Printliminator/commit/18bb628ab61b5eb3bb07c0fec6af913e9bb7cb14#diff-2

Thank you!

**Comment by yukulele** [comment]
Parfait !

**Comment by yukulele** [comment]
need I also translate `description` properties?

**Comment by Mottie** [comment]
Nope, you've taken care of it! Thank you again.

**Pull request merged**
